modLoader="javafml"
loaderVersion="[36,)"

license="MIT"
issueTrackerURL="https://github.com/Hellish-Mods/reignited-utilities/issues"

[[mods]]
modId="reignitedutilities"
version="${file.jarVersion}"

displayName="Reignited Utilities"
displayURL="https://www.curseforge.com/minecraft/mc-mods/reignited-utilities"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
G_cat (Coding, Russian translation)
Rainbuu (Coding, textures)
bigbee (Textures)
Kasualix (Simplified Chinese translation)
"""

description="A port/rewrite/reimagining of Extra Utilities 2 and 1 for 1.16.5"

[[dependencies.reignitedutilities]]
    modId="forge"
    mandatory=true

    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reignitedutilities]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.reignitedutilities]]
    modId="jei"
    mandatory=false

    versionRange=","
    ordering="AFTER"
    side="BOTH"

[[dependencies.reignitedutilities]]
    modId="create"
    mandatory=false

    versionRange=","
    ordering="AFTER"
    side="BOTH"
[[dependencies.reignitedutilities]]
    modId="thermal"
    mandatory=false

    versionRange=","
    ordering="AFTER"
    side="BOTH"